### ISSUE TITLE
Allow for users to specify element and modifier delimiters.

### ISSUE THREAD

**Issue by SethTompkins** [rebem/classname#2]
First off, great package :)

The only thing that keeps me from using this is the hard-coded `_` used to delimit modifiers. Traditional BEM syntax has modifiers delimited by two dashes, `--`.

In order to cater to more BEM flavors, it would be great to be able to set custom delimiters for the package.

**Comment by Guria** [comment]
@SethTompkins in fact this package represents traditional syntax, but what you mention is Harry Roberts' one. See https://en.bem.info/method/naming-convention/

**Comment by Guria** [comment]
@SethTompkins you can find useful [bem-cn](https://github.com/albburtsev/bem-cn) and some [other similar projects](https://github.com/albburtsev/bem-cn/issues/17)

**Comment by deepsweet** [comment]
hi.

first of all, "traditional" BEM syntax delimiters are [underscores](https://en.bem.info/method/naming-convention/), everything else - BEM variations.

the only (pretty) way to implement this without headaches is to use some special `process.env` (and most likely we will do it so, because this feature request may be popular), but our original idea was to stop thinking in terms of delimiters and start using [rebem-css](https://github.com/rebem/css). in that way you don't write delimteters by hands in any of the technologies in stack.

**Comment by Guria** [comment]
@deepsweet I like idea with `process.env`. We already have several projects with delimeters configured in runtime, like `bem-cn`. But we are really not often have such need.

**Comment by deepsweet** [comment]
`process.env.REBEM_MOD_DELIM` and `process.env.REBEM_ELEM_DELIM`?

webpack config example:

``` js
plugins: [
    new webpack.DefinePlugin({
        'process.env': {
            REBEM_MOD_DELIM: JSON.stringify('--'),
            REBEM_ELEM_DELIM: JSON.stringify('~~')
        }
    })
]
```

**Comment by SethTompkins** [comment]
Sorry for my presumptuousness, and thanks for pointing me in the right direction.
